<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calculadora</title>
</head>


<body>
    <div class="todo">
        <div class="child">
            <div class="calc-container">
                <form method="POST">
                    <div class="btn">
                        <input class="display" type="text" name="resultado" value="<?php echo isset($_SESSION['num1']) ? $_SESSION['num1'] : '0'; ?>" readonly><br>
                        <button type="submit" name="numero" value="7">7</button>
                        <button type="submit" name="numero" value="8">8</button>
                        <button type="submit" name="numero" value="9">9</button>
                        <button type="submit" name="numero" value="/">/</button><br>
                        <button type="submit" name="numero" value="4">4</button>
                        <button type="submit" name="numero" value="5">5</button>
                        <button type="submit" name="numero" value="6">6</button>
                        <button type="submit" name="numero" value="*">*</button><br>
                        <button type="submit" name="numero" value="1">1</button>
                        <button type="submit" name="numero" value="2">2</button>
                        <button type="submit" name="numero" value="3">3</button>
                        <button type="submit" name="numero" value="-">-</button><br>
                        <button type="submit" name="numero" value="0">0</button>
                        <button type="submit" name="numero" value=",">,</button>
                        <button type="submit" name="numero" value="%">%</button>
                        <button type="submit" name="numero" value="+">+</button><br>
                        <button type="submit" name="numero" value="←">←</button>
                        <button type="submit" name="numero" value="c">c</button>
                        <button type="submit" name="numero" value="=">=</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>