<?php
session_start();
if (isset($_POST['numero'])) {
    switch ($_POST['numero']) {
        case "c":
            $_SESSION['num1'] = null;
            $_SESSION['operacion'] = null;
            break;
        case "←":
            $_SESSION['num1'] = substr($_SESSION['num1'], 0, -1);
            break;
        case "+":
        case "-":
        case "*":
        case "/":
        case "%":
            if (isset($_SESSION['num1'])) {
                $_SESSION['operacion'] = $_POST['numero'];
                $_SESSION['num2'] = $_SESSION['num1'];
                $_SESSION['num1'] = null;
            }
            break;
        case "=":
            if (isset($_SESSION['num1']) && isset($_SESSION['operacion']) && isset($_SESSION['num2'])) {
                $num1 = floatval($_SESSION['num2']);
                $num2 = floatval($_SESSION['num1']);
                $operacion = $_SESSION['operacion'];

                switch ($operacion) {
                    case "+":
                        $_SESSION['num1'] = $num1 + $num2;
                        break;
                    case "-":
                        $_SESSION['num1'] = $num1 - $num2;
                        break;
                    case "*":
                        $_SESSION['num1'] = $num1 * $num2;
                        break;
                    case "/":
                        $_SESSION['num1'] = $num1 / $num2;
                        break;
                    case "%":
                        $_SESSION['num1'] = $num1 % $num2;
                        break;
                }
                $_SESSION['num2'] = null;
                $_SESSION['operacion'] = null;
            }
            break;
        default:
            if (isset($_SESSION['num1'])) {
                $_SESSION['num1'] .= $_POST['numero'];
            } else {
                $_SESSION['num1'] = $_POST['numero'];
            }
            break;
    }
}
?>


<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calculadora</title>
</head>


<body>
    <div class="todo">
        <div class="child">
            <div class="calc-container">
                <form method="POST">
                    <div class="btn">
                        <input class="display" type="text" name="resultado" value="<?php echo isset($_SESSION['num1']) ? $_SESSION['num1'] : '0'; ?>" readonly><br>
                        <button type="submit" name="numero" value="7">7</button>
                        <button type="submit" name="numero" value="8">8</button>
                        <button type="submit" name="numero" value="9">9</button>
                        <button type="submit" name="numero" value="/">/</button><br>
                        <button type="submit" name="numero" value="4">4</button>
                        <button type="submit" name="numero" value="5">5</button>
                        <button type="submit" name="numero" value="6">6</button>
                        <button type="submit" name="numero" value="*">*</button><br>
                        <button type="submit" name="numero" value="1">1</button>
                        <button type="submit" name="numero" value="2">2</button>
                        <button type="submit" name="numero" value="3">3</button>
                        <button type="submit" name="numero" value="-">-</button><br>
                        <button type="submit" name="numero" value="0">0</button>
                        <button type="submit" name="numero" value=",">,</button>
                        <button type="submit" name="numero" value="%">%</button>
                        <button type="submit" name="numero" value="+">+</button><br>
                        <button type="submit" name="numero" value="←">←</button>
                        <button type="submit" name="numero" value="c">c</button>
                        <button type="submit" name="numero" value="=">=</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>